services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./services:/app/services
    command: poetry run uvicorn services.api.main:app --host 0.0.0.0 --port 8000 --reload

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    environment:
      - IS_PERSISTENT=FALSE
    ports:
      - "8001:8000"
